---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: centos
    tag: "7"
inputs:
- name: ccp_src
- name: cluster_env_files
- name: check-gpdb_src

run:
  path: check-gpdb_src/ci/scripts/check-gpdb.sh
