---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: centos
    tag: "7"

inputs:
- name: terraform
- name: gpdb_binary
- name: ccp_src
- name: gpdb_src

outputs:
- name: cluster_env_files

run:
  path: ccp_src/aws/gen_cluster.sh
